version: "3"

services:
  drill-admin:
    image: drill4j/admin:${BACK_VERSION}
    environment:
      TEST2CODE_PLUGIN_VERSION: ${TEST2CODE_PLUGIN_VERSION}
      LOG_LEVEL: ${LOG_LEVEL}

    ports:
      - 8090:8090
    networks:
      - drill4j
    volumes:
     - admin:/work

  admin-ui:
    image: drill4j/admin-ui-root-config:${FRONT_VERSION}
    restart: always
    ports:
      - 8091:8080
    environment:
      UPSTREAM: drill-admin:8090
      UI_PLUGINS_URLS: test2code#https://cdn.jsdelivr.net/npm/@drill4j/test2code-ui@${TEST2CODE_UI_VERSION}/dist/Drill4J-test-to-code.js
    networks:
      - drill4j

networks:
  drill4j:

volumes:
  admin:
